[features]
seeds = false
skip-lint = false
[programs.devnet]
football_daos = "3Sz5VQ2VnxZsgTsGrJqUSbpfM4H4efMm8QCFqLtq6WjN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/rayhan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
